trigger: none
variables:
  Subscription: 'afdc32d4-a9f7-4ea6-9bff-e8c5aa1ed52f'
  RG: 'PJ-Dev-Network'
  env: 'dev'
  location: 'uksouth'
  TemplatePath: '$(System.DefaultWorkingDirectory)/'
  ParamsPath: '$(System.DefaultWorkingDirectory)/Templates/Parameters/'

jobs:
- job: DeployHub
  displayName: 'Depoly hub'
  pool:
    vmImage: 'ubuntu-latest'    
  variables:
    template: 'network-hub.bicep'
  steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'DeployHubVnet'
      inputs:
        subscriptionId: $(Subscription)
        ConnectedServiceName: 'devsp'
        resourceGroupName: $(RG)
        deploymentScope: Resource Group
        deploymentMode: Incremental
        location: $(location)
        templateLocation: Linked artifact
        csmFile: '$(TemplatePath)$(template)'
        csmParametersFile: '$(ParamsPath)$(env).parameters.json'
        deploymentOutputs: huboutputs

- job: showoutputs
  displayName: 'showOutput'
  dependsOn: 'DeployHub'
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: PowerShell@1
      inputs:
        scriptType: inlineScript
        inlineScript: "$outputstring = $(huboutputs) | write-host $outputstring"

# - job: getoutputs
#   displayName: 'getoutputs'
#   dependsOn: 'DeployHub'
#   pool:
#     vmImage: 'windows-latest'
#   steps:
#     - task: PowerShell@2
#       displayName: runscript
#       inputs:
#         filePath: '$(System.DefaultWorkingDirectory)/parse_ARM_outputs.ps1'
#         arguments: -ArmOutputString '$(huboutputs)' -MakeOutput -ErrorAction Stop
        


- job: Deployspokes
  displayName: 'Depoly spokes'
  dependsOn: 'showoutputs'
  pool:
    vmImage: 'ubuntu-latest'    
  variables:
    template: 'network-spokes.bicep'
  steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'DeploySpokes'
      inputs:
        subscriptionId:       $(Subscription)
        ConnectedServiceName: 'devsp'
        resourceGroupName:    $(RG)
        deploymentScope:      Resource Group
        deploymentMode:       Incremental
        location:             $(location)
        templateLocation:     Linked artifact
        csmFile:              '$(TemplatePath)$(template)'
        csmParametersFile:    '$(ParamsPath)$(env).parameters.json'
        deploymentOutputs:    spokeOutputs
        
          



  
        
        